import type { HostInventory } from './hostDetector.js';

export interface NixEmitterParams {
  projectName: string;
  hostInventory: HostInventory;
  hasMongo: boolean;
}

export function generateFlakeNix(params: NixEmitterParams): string {
  const nodePkg = params.hostInventory.nodeMajor >= 22
    ? 'nodejs_22'
    : params.hostInventory.nodeMajor >= 20
    ? 'nodejs_20'
    : 'nodejs_22';

  const extraPkgs: string[] = [];
  if (params.hasMongo) {
    extraPkgs.push('mongosh');
  }

  if (params.hostInventory.packageManager === 'pnpm') {
    extraPkgs.push('nodePackages.pnpm');
  } else if (params.hostInventory.packageManager === 'yarn') {
    extraPkgs.push('nodePackages.yarn');
  } else if (params.hostInventory.packageManager === 'bun') {
    extraPkgs.push('bun');
  }

  const pkgsList = [nodePkg, ...extraPkgs].map((p) => `            ${p}`).join('\n');

  return `{
  description = "Hermetic development environment for ${params.projectName} generated by BackForge";

  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/nixos-unstable";
    flake-utils.url = "github:numtide/flake-utils";
  };

  outputs = { self, nixpkgs, flake-utils }:
    flake-utils.lib.eachDefaultSystem (system:
      let
        pkgs = import nixpkgs { inherit system; };
      in
      {
        devShells.default = pkgs.mkShell {
          buildInputs = with pkgs; [
${pkgsList}
          ];

          shellHook = ''
            echo "🔨 BackForge hermetic devshell active for ${params.projectName}"
            echo "Node: $(${nodePkg.replace('_', ' ')} --version 2>/dev/null || node --version)"
            echo "Package Manager: ${params.hostInventory.packageManager}"
          '';
        };
      }
    );
}
`;
}

export function generateShellNix(params: NixEmitterParams): string {
  const nodePkg = params.hostInventory.nodeMajor >= 22
    ? 'nodejs_22'
    : params.hostInventory.nodeMajor >= 20
    ? 'nodejs_20'
    : 'nodejs_22';

  const extraPkgs: string[] = [];
  if (params.hasMongo) {
    extraPkgs.push('mongosh');
  }

  if (params.hostInventory.packageManager === 'pnpm') {
    extraPkgs.push('nodePackages.pnpm');
  } else if (params.hostInventory.packageManager === 'yarn') {
    extraPkgs.push('nodePackages.yarn');
  } else if (params.hostInventory.packageManager === 'bun') {
    extraPkgs.push('bun');
  }

  const pkgsList = [nodePkg, ...extraPkgs].map((p) => `    ${p}`).join('\n');

  return `{ pkgs ? import <nixpkgs> {} }:

pkgs.mkShell {
  buildInputs = with pkgs; [
${pkgsList}
  ];

  shellHook = ''
    echo "🔨 BackForge hermetic devshell active for ${params.projectName}"
    echo "Node: $(node --version)"
  '';
}
`;
}
